[workspace]
resolver = "2"
members = [
    "syngui",
    "app/calculator",
    "app/widget_gallery_mss",
    "app/linamp",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
rust-version = "1.85"
authors = ["Alexeyev Vitaly"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rubato = "0.16"
